"""Module pulling out the relevant types from the protobuf autogenerated code"""

from pysparkplug._protobuf import sparkplug_b_pb2

Payload = sparkplug_b_pb2.Payload  # type: ignore[attr-defined]
DataSet = Payload.DataSet
DataSetValue = DataSet.DataSetValue
DataSetValueExtension = DataSetValue.DataSetValueExtension
Row = DataSet.Row
MetaData = Payload.MetaData
Metric = Payload.Metric
MetricValueExtension = Metric.MetricValueExtension
PropertySet = Payload.PropertySet
PropertySetList = Payload.PropertySetList
PropertyValue = Payload.PropertyValue
PropertyValueExtension = PropertyValue.PropertyValueExtension
Template = Payload.Template
Parameter = Template.Parameter
ParameterValueExtension = Parameter.ParameterValueExtension
DataType = sparkplug_b_pb2.DataType  # type: ignore[attr-defined]
